# Inserire qui le variabili d'ambiente
custom:
  envConfigMap:
    MY_VAR: myvalue
  envSecret:
    MY_SECRET: mysecretvalue
    
ingress:
  fqdn: kubernetes.docker.internal


#Override dei valori presenti in values.yaml
resources:
     limits:
       cpu: 250m
       memory: 512Mi
     requests:
       cpu: 250m
       memory: 512Mi

probes:
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 120
    periodSeconds: 60
    successThreshold: 1
    tcpSocket:
      port: tcp
    timeoutSeconds: 1
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 120
    periodSeconds: 60
    successThreshold: 1
    tcpSocket:
      port: tcp
    timeoutSeconds: 1