apiVersion: apps/v1
kind: Deployment
{{- $prefix := include "my-helm.fullname" . }}
metadata:
  name: {{ include "my-helm.fullname" . }}-deployment
  labels:
    app: {{ include "my-helm.fullname" . }}-deployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ include "my-helm.fullname" . }}-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "my-helm.fullname" . }}-deployment
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: main-container
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.service.targetPort }}
          ports:
            - name: tcp
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- with .Values.probes }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
          {{- if .Values.custom.envConfigMap }}
           - configMapRef:
              name: {{ include "my-helm.fullname" . }}-env
          {{- end }}
          {{- if .Values.custom.envSecret }}
           - secretRef:
              name: {{ include "my-helm.fullname" . }}-env
          {{- end }}
#          volumeMounts:
#            - name: {{ include "my-helm.fullname" . }}-application-yaml-volume
#             mountPath: /opt/api/config/application.yaml
#              subPath: application.yaml
#      volumes:
#        - name: {{ include "my-helm.fullname" . }}-application-yaml-volume
#          configMap:
#             name: {{ include "my-helm.fullname" . }}-application-yaml-volume


