{{- if .Values.ingress.enabled -}}
{{- $fullName := include "my-helm.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    app: {{ include "my-helm.fullname" . }}-depl-2-svc-app-lbl
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.fqdn | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  spec:
  rules:
    - host: {{ .Values.ingress.fqdn | quote }}
      http:
        paths:
          - backend:
              serviceName: {{ include "my-helm.fullname" . }}-service
              servicePort: {{ .Values.service.port }}   
          - path: /image-compressor
            backend:
              serviceName: {{ include "my-helm.fullname" . }}-service
              servicePort: {{ .Values.service.port }}
  {{- end }}
