{{- if .Values.custom.envSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-helm.fullname" . }}-env
type: Opaque
data:
{{- range $key, $val := .Values.custom.envSecret }}
{{ $key | indent 2}}: {{ $val | b64enc }}
{{- end}}
{{- end}}
