{{- if .Values.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm.fullname" . }}-service
  labels:
    app: {{ include "my-helm.fullname" . }}-deployment
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: TCP
      name: tcp
  selector:
    app: {{ include "my-helm.fullname" . }}-deployment
{{- end}}
