#FROM adorsys/nginx:ubi
FROM nginx:stable

#docker build --build-arg http_proxy=${http_proxy} --build-arg https_proxy=${http_proxy} --build-arg no_proxy=${no_proxy} --no-cache 

#RUN apt-get update -qqy && apt-get install -qqy wget vim telnet && apt-get clean && rm -rf /var/lib/apt/lists/*

ADD DEVOPS/nginx/nginx.conf /etc/nginx/conf.d/default.template
ADD DEVOPS/nginx/default.conf  /
ADD DEVOPS/nginx/default-override.conf /
RUN rm -f /etc/nginx/conf.d/default.conf

#nr USER root
RUN mkdir -p /etc/nginx/cert && mkdir -p /var/log/ && mkdir -p /var/log/nginx 
#nr RUN chown -R 1001:0 /etc/nginx/cert /var/log/ /var/log/nginx

ADD DEVOPS/cert/*.crt /etc/nginx/cert
ADD DEVOPS/cert/*.key /etc/nginx/cert
RUN ls -la /etc/nginx/cert

ADD nginx/nginx-epoint.sh /
RUN chmod +x /nginx-epoint.sh

#RUN cd /etc/nginx/cert && ls -la *Chain* && cat example.org.crt $(ls -la *Chain*) > $(ls -la *.crt) || true
#USER 1001
ENTRYPOINT  ["/bin/bash", "-c", "/nginx-epoint.sh"]
